#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

KAGGLE_JSON="$HOME/.kaggle/kaggle.json"
COMPETITION="spaceship-titanic"

banner "Kaggle API access for $COMPETITION"

# ── Stage 1: CLI available via the project's uv env ───────────────────────
stage "Install the kaggle CLI (uv env)"
say "The kaggle package is already a dependency in pyproject.toml, so this is"
say "just syncing the project's virtualenv — no manual step here."
if command -v uv >/dev/null 2>&1; then
  uv sync
  if uv run kaggle --version; then
    say "kaggle CLI is available as: uv run kaggle ..."
  else
    warn "uv run kaggle --version failed; check the uv sync output above."
  fi
else
  warn "uv not found on PATH — install uv first, then re-run this wizard."
  SKIPPED+=("uv sync / kaggle CLI check — uv not found")
fi
pause "Press Enter once that looks good"

# ── Stage 2: create and place the API token ────────────────────────────────
stage "Create your Kaggle API token"
if [[ -f "$KAGGLE_JSON" ]]; then
  note "Found an existing token at $KAGGLE_JSON — keeping it."
  note "(Delete it first if you want to replace it with a fresh one.)"
else
  say "We need a personal API token; Kaggle only shows it once, at creation."
  open_url "https://www.kaggle.com/settings"
  step "Scroll to the API section."
  step "Click 'Create New Token'. Your browser downloads a file named kaggle.json."
  pause "Downloaded it? Press Enter to continue"

  DOWNLOADED=""
  ask DOWNLOADED "Full path to the downloaded kaggle.json (e.g. ~/Downloads/kaggle.json):"
  DOWNLOADED="${DOWNLOADED/#\~/$HOME}"

  if [[ -f "$DOWNLOADED" ]]; then
    mkdir -p "$HOME/.kaggle"
    mv "$DOWNLOADED" "$KAGGLE_JSON"
    chmod 600 "$KAGGLE_JSON"
    printf '  %s✓ moved%s token to %s (chmod 600)\n' "$GREEN" "$RESET" "$KAGGLE_JSON"
  else
    warn "couldn't find a file at that path — move it to $KAGGLE_JSON by hand,"
    warn "then re-run this wizard; it will pick up the existing file."
    SKIPPED+=("place kaggle.json at $KAGGLE_JSON")
  fi
fi
note "Never commit this file — .gitignore already excludes kaggle.json, and"
note "~/.kaggle/ sits outside this repo entirely."

# ── Stage 3: accept competition rules ──────────────────────────────────────
stage "Accept the competition rules"
say "The API rejects submissions until rules are accepted for $COMPETITION."
open_url "https://www.kaggle.com/competitions/$COMPETITION/rules"
step "Scroll down and click 'I Understand and Accept' (skip if already accepted)."
confirm "Rules accepted for $COMPETITION?" || warn "submit will fail with 403 until you accept them."

# ── Stage 4: verify API access actually works ──────────────────────────────
stage "Verify API access"
say "A read-only call that proves the token + accepted rules both work,"
say "without using up a submission."
if command -v uv >/dev/null 2>&1; then
  if uv run kaggle competitions submissions -c "$COMPETITION"; then
    say "Auth works: that listed your submissions (or showed none yet) for $COMPETITION."
  else
    warn "That call failed — recheck the token file and rules acceptance above, then re-run."
    SKIPPED+=("kaggle API verification call")
  fi
else
  warn "uv not found — can't verify from here."
fi
pause "Press Enter to continue"

# ── Stage 5: read the facts this ticket needs recorded ─────────────────────
stage "Read the submission limit and test split"
say "These numbers are stated on Kaggle's pages, not in the API."
open_url "https://www.kaggle.com/competitions/$COMPETITION/submissions"
step "Find the daily submission limit (usually phrased like 'You may submit N entries per day')."
ask SUBMIT_LIMIT "Daily submission limit for $COMPETITION:"
open_url "https://www.kaggle.com/competitions/$COMPETITION/leaderboard"
step "Check the leaderboard page/rules for a stated public/private test split (e.g. '35% public / 65% private')."
step "If it isn't stated anywhere, just type: not stated"
ask PUBLIC_PRIVATE_SPLIT "Public/private split of the test set (or 'not stated'):"

finish

# ── Resolution summary: paste this into the ticket's resolution comment ───
printf '\n%s%s  Paste into the resolution comment%s\n\n' "$BOLD" "$BLUE" "$RESET"
cat <<EOF
- **Credential location:** \`$KAGGLE_JSON\` (outside the repo; \`.gitignore\` also
  excludes any \`kaggle.json\` that lands inside it). A session reaches it as
  the ambient \`~/.kaggle/kaggle.json\` the \`kaggle\` package reads automatically —
  nothing repo-side needs to point at it.
- **Working invocation** (from a real run):
  \`uv run kaggle competitions submit -c $COMPETITION -f submissions/<config>.csv -m "<message>"\`
- **Daily submission limit:** $SUBMIT_LIMIT
- **Public/private split:** $PUBLIC_PRIVATE_SPLIT
EOF
